# Site Settings
title: Pravas
description: Official website for Pravas
url: "https://pravas.org"
baseurl: ""

# Plugins
plugins:
  - jekyll-sitemap

# Files/Folders to ignore during build
exclude:
  - README.md
  - README.txt
  - LICENSE.txt
